<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestionJ_biblioteca\GestionJ_biblioteca.csproj" />
    <ProjectReference Include="..\Presentaciones_biblioteca\Presentaciones_biblioteca.csproj" />
  </ItemGroup>

</Project>
